version: 2.1

jobs:
  terraform_init:
    docker:
      - image: hashicorp/terraform:light
    working_directory: /tmp/project
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: terraform init

  terraform_fmt:
    docker:
      - image: hashicorp/terraform:light
    working_directory: /tmp/project
    steps:
      - checkout
      - run:
          name: Format Terraform Code
          command: terraform fmt -check

  terraform_validate:
    docker:
      - image: hashicorp/terraform:light
    working_directory: /tmp/project
    steps:
      - checkout
      - run:
          name: Validate Terraform Configuration
          command: terraform validate

  terraform_plan:
    docker:
      - image: hashicorp/terraform:light
    working_directory: /tmp/project
    steps:
      - checkout
      - run:
          name: Plan Terraform Changes
          command: terraform plan -out=tfplan

  terraform_apply:
    docker:
      - image: hashicorp/terraform:light
    working_directory: /tmp/project
    steps:
      - checkout
      - run:
          name: Apply Terraform
          command: terraform apply -auto-approve tfplan

  terraform_destroy:
    docker:
      - image: hashicorp/terraform:light
    working_directory: /tmp/project
    steps:
      - checkout
      - run:
          name: Destroy Terraform Resources
          command: terraform destroy -auto-approve

workflows:
  version: 2
  plan_and_apply:
    jobs:
      - terraform_init
      - terraform_fmt:
          requires:
            - terraform_init
      - terraform_validate:
          requires:
            - terraform_fmt
      - terraform_plan:
          requires:
            - terraform_validate
      - terraform_apply:
          requires:
            - terraform_plan
          filters:
            branches:
              only:
                - us-dev  # Apply only on commits to the main branch

  destroy:
    jobs:
      - terraform_destroy:
          filters:
            branches:
              only:
                - destroy  # Run destroy job only when pushing to a branch named "destroy"
