version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./us-dev/ec2
      - terraform/validate:
          path: ./us-dev/ec2
      - terraform/init:
          path: ./us-dev/ec2
      - terraform/plan:
          path: ./us-dev/ec2
          persist-workspace: true
          requires:
          - terraform/validate
      - terraform/apply:
          path: ./us-dev/ec2
          attach-workspace: true
          filters:
            branches:
              only: us-dev
      - terraform/destroy:
          path: ./us-dev/ec2
    working_directory: ~/project
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle
