version: 2.1

jobs:
  build:
    docker:
      # - image: circleci/python:3.7  # Use the CircleCI Docker image with AWS CLI
      - image: cimg/aws:2024.03  # Use the CircleCI Docker image with AWS CLI

    steps:
      - checkout  # Checkout the code from GitHub

      # Run AWS CLI command
      - run:
          name: Deploy CloudFormation Stack
          command: |
            aws cloudformation delete-stack --stack-name BasicEC2
            #--template-body file://us-dev/ec2/ec2-test.yml

  # approve_deletion:
  #   type: approval

  # delete_stack:
  #   docker:
  #     - image: cimg/aws:2024.03
      
  #   steps:
  #     - checkout
  #     - run:
  #         name: Delete CloudFormation Stack
  #         command: |
  #           aws cloudformation delete-stack --stack-name BasicEC2
  #           aws cloudformation wait stack-delete-complete --stack-name BasicEC2
  #           echo "Stack deletion initiated."


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build

      # - delete_stack:
      #     requires:
      #       - approve_deletion
        