version: 2.1

jobs:
  terraform:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: |
            cd ./us-dev/ec2
            terraform init
            terraform -check
            terraform -out=tfplan
            terraform -auto-approve tfplan
            terraform destroy -auto-approve


workflows:
  version: 2
  plan_and_apply:
    jobs:
      - terraform:
          filters:
            branches:
              only:
                - us-dev  # Apply only on commits to the main branch

  destroy:
    jobs:
      - terraform_destroy:
          filters:
            branches:
              only:
                - destroy  # Run destroy job only when pushing to a branch named "destroy"
