version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7  # Use the CircleCI Docker image with AWS CLI

    steps:
      - checkout  # Checkout the code from GitHub

      # Install AWS CLI
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get install -y awscli


      # Run AWS CLI command
      - run:
          name: Deploy CloudFormation Stack
          command: |
            aws cloudformation create-stack --stack-name BasicEC2 --template-body file://us-dev/ec2/ec2-test.yml

workflows:
  version: 2
  build:
    jobs:
      - build