version: 2.1

jobs:
  terraform:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: |
            terraform -chdir=./us-dev/ec2 init
            terraform -chdir=./us-dev/ec2 -check
            terraform -chdir=./us-dev/ec2 -out=tfplan
            terraform -chdir=./us-dev/ec2 -auto-approve tfplan
            terraform -chdir=./us-dev/ec2 destroy -auto-approve


workflows:
  version: 2
  plan_and_apply:
    jobs:
      - terraform:
          filters:
            branches:
              only:
                - us-dev  # Apply only on commits to the main branch
