version: 2.1

jobs:
  build:
    docker:
      - image: circleci/aws-cli:latest  # Use the CircleCI Docker image with AWS CLI

    steps:
      - checkout  # Checkout the code from GitHub

      # Run AWS CLI command
      - run:
          name: Deploy CloudFormation Stack
          command: |
            aws cloudformation create-stack --stack-name BasicEC2 --template-body file://ec2/ec2-test.yml

workflows:
  version: 2
  build:
    jobs:
      - build